on:
  push:
    branches:
      - master

name: "shell"
permissions: {}

jobs:
  shellcheck:
    name: shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run shell
        uses: ludeeus/action-shell@master
